# SPDX-License-Identifier: 0BSD

name: Solaris

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions: {}

jobs:
  Solaris:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Solaris
    steps:
      - uses: actions/checkout@v4

      - name: Test in Solaris
        uses: vmactions/solaris-vm@47bea106d03acaf91084e52548ee460556011602 #v1.1.8
        with:
          release: 11.4-gcc
          usesh: true
          run: |
            set -e
            uname -a
            # /usr/xpg4/bin isn't in PATH by default.
            echo "Environment variable PATH: $PATH"
            ./autogen.sh --no-po4a
            ./configure --disable-static --enable-debug --enable-werror
            make check
